### PR TITLE
Add gamedata/spells endpoint

### PR DESCRIPTION
**Pull request by VeryGreatFrog**
This should have existed.
https://avrae.readthedocs.io/en/stable/automation_ref.html#CastSpell.id

### Summary
Add the endpoint for spells gamedata that should have existed according to the documentation. There is no other way to get this data, as gamedata/entitlements is incomplete when it comes to SRD spells.

#### PR Type

- [ ] This PR is a code change that implements a feature request.
- [X] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
#### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by VeryGreatFrog** [comment]
Having finally been able to test it, this endpoint actually shows more data than I was expecting. Hold on tight for some changes

**Comment by VeryGreatFrog** [comment]
Tested and works as expected. 
image
ready to merge @SeanStoves

**Comment by VeryGreatFrog** [comment]
Alternatively, it can also be changed to show similar to how entitlements show their data, with their type, link to beyond, entity type, etc, but I don't think that is terribly useful.

**Comment by SeanStoves** [comment]
@VeryGreatFrog , if you can run blackify on it, I'll get it merged ;)

**Comment by VeryGreatFrog** [comment]
@SeanStoves I gotta be honest, I don't have that set up well and it is failing not on my code, so not something I am going to concern myself with!

**Pull request merged**
